sudo: required
language: C
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y cmake subversion ninja-build build-essential zlib1g-dev libffi-dev libedit-dev libncurses5-dev libboost-dev
- svn co -q http://llvm.org/svn/llvm-project/llvm/tags/RELEASE_391/final llvm
- cd llvm/tools
- svn co -q http://llvm.org/svn/llvm-project/cfe/tags/RELEASE_391/final clang
- mkdir ../build && cd ../build
- CC=gcc CXX=g++ cmake -DLLVM_ENABLE_CXX1Y=true -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGET_ARCH="X86" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_FFI=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -G Ninja ..
#- ninja && sudo ninja install
- sudo ls /usr/bin
- sudo ls /usr/local
- sudo ls /usr/local/bin
- sudo ls /usr/local/clang
- sudo ls /usr/local/llvm
- sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/local/bin/clang 100
- sudo update-alternatives --install /usr/bin/clang clang /usr/local/bin/clang 100
- sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/local/bin/llvm-config 100
- llvm-config --version
- clang --version
install:
- cd ../..
- mkdir build
- cd build
- LLVM_LIBS="$(llvm-config --components)" && sed -i "s/insert-llvm-libs-here/${LLVM_LIBS}/g" ../CMakeLists.txt
- sed -i "s/all-targets //g" ../CMakeLists.txt
- sudo sed -i 's/list(APPEND link_components "jit")/list(APPEND link_components "mcjit")/g' /usr/lib/cmake/llvm/LLVM-Config.cmake
- cmake .. -G Ninja
- ninja
- sudo ninja-install
script:
- llvm-config --version
- clang --version
- clang-chimera -version
