sudo: required
language: C
cache:
    directories:
        $TRAVIS_BUILD_DIR/llvm
        $TRAVIS_BUILD_DIR/cmake-3.14.0-rc4
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y cmake ninja-build build-essential zlib1g-dev libffi-dev libedit-dev libncurses5-dev libboost-dev
- sudo apt-get purge -y -qq libllvm3.4 llvm-3.4 llvm* libllvm* clang*
- sudo rm -Rf /usr/local/clang
- sudo rm -Rf /usr/local/clang-5.0.0
- /bin/bash -c "if [ ! -d \"llvm/.git\" ] ; then git clone https://github.com/llvm-mirror/llvm.git llvm && cd llvm && git checkout release_39 && cd tools && git clone https://github.com/llvm-mirror/clang.git clang && cd clang && git checkout release_39; fi"
- cd llvm
- mkdir -p build && cd build
- CC=gcc CXX=g++ cmake -DLLVM_ENABLE_CXX1Y=true -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGET_ARCH="X86" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_FFI=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -G Ninja ..
- ninja && sudo ninja install
- cd ../..
- sudo apt remove --purge --auto-remove cmake
- sudo apt purge --auto-remove cmake
- wget https://github.com/Kitware/CMake/releases/download/v3.14.0-rc4/cmake-3.14.0-rc4.tar.gz > /dev/null
- tar xfz cmake-3.14.0-rc4.tar.gz --skip-old-files
- cd cmake-3.14.0-rc4
- ./bootstrap
- make -j4 && sudo make install
- cmake --version
- cd ..
install:
- sudo sed -i 's/list(APPEND link_components "jit")/list(APPEND link_components "mcjit")/g' /usr/lib/cmake/llvm/LLVM-Config.cmake
- chmod +x run_cmake
- ./run_cmake
- cd build
- ninja
- sudo ninja install
script:
- llvm-config --version
- clang --version
- clang-chimera -version
